services:
  - type: web
    name: neverlucky-backend
    env: docker
    branch: master
    dockerfilePath: backend/Dockerfile
    autoDeploy: true

  - type: web
    name: neverlucky-frontend
    env: static
    branch: master
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/dist
    autoDeploy: true
