services:
  - type: web
    name: neverlucky-backend
    env: docker
    branch: master
    plan: free
    dockerfilePath: backend/Dockerfile
    autoDeploy: true

  - type: web
    name: neverlucky-frontend
    env: docker
    branch: master
    plan: free
    dockerfilePath: frontend/Dockerfile
    autoDeploy: true
