services:
  - type: web
    name: neverlucky-backend
    env: docker
    branch: master
    plan: free
    rootDir: backend
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: JWT_SECRET
        fromDatabase:
          name: JWT_SECRET
          encryption: sse
