services:
  - type: web
    name: neverlucky-backend
    env: docker
    branch: master
    plan: free
    dockerfilePath: backend/Dockerfile
    autoDeploy: true

  - type: static
    name: neverlucky-frontend
    env: static
    branch: master
    plan: free
    buildCommand: cd frontend && npm ci && npm run build
    publishPath: frontend/dist
    autoDeploy: true
