services:
  - type: web
    name: neverlucky-backend
    env: docker
    branch: master
    plan: free
    dockerfilePath: backend/Dockerfile
    autoDeploy: true

  - type: static_site
    name: neverlucky-frontend
    branch: master
    buildCommand: cd frontend && npm ci && npm run build
    publishPath: frontend/dist
    autoDeploy: true
